### ISSUE TITLE
Move plugin logic to core-bundle

### ISSUE THREAD

**Issue by Toflar** [contao/manager-bundle#13]
Most of the stuff listed in https://github.com/contao/manager-bundle/blob/develop/src/ContaoManager/Plugin.php should go to the core-bundle.

**Comment by Toflar** [comment]
See https://github.com/contao/manager-bundle/pull/14

**Comment by leofeyer** [comment]
I disagree. We need to distinguish between the core bundle and the standard edition here; and the core bundle must not configure anything but itself. The manager bundle is responsible for configuring the _application_, meaning everything that is configured in the standard edition.

**Comment by Toflar** [comment]
Yeah, but imho stuff that is in that plugin now, does not belong there. E.g. the `KnpTimeBundle`.

**Comment by leofeyer** [comment]
Yes, that's true.

**Comment by aschempp** [comment]
closed in favor of #18
