### ISSUE TITLE
InstallTool logException

### ISSUE THREAD

**Issue by ghost** [contao/manager-bundle#17]
<a href="https://github.com/digitalingenieur"><img src="https://avatars.githubusercontent.com/u/13146301?v=3" align="left" width="42" height="42"></img></a> [Issue](https://github.com/contao/installation-bundle/issues/41) by @digitalingenieur
February 7th, 2017, 11:14 GMT

In Contao Managed Version the path to the log file should be something like

`$this->rootDir.'/../var/logs/prod-'.date('Y-m-d').'.log'`

in InstallTool.php, Line 395

**Comment by aschempp** [comment]
@leofeyer did you move this here? The `manager-bundle` does not have a `InstallTool` class?

**Comment by leofeyer** [comment]
But the error does not occur in the standard edition, so …

**Comment by aschempp** [comment]
@leofeyer not true, this is an issue of moving to the Symfony 3 structure.

**Comment by leofeyer** [comment]
You are right. I have re-opened the [original issue](https://github.com/contao/installation-bundle/issues/41).
