### ISSUE TITLE
[4.4-beta1] kernel.project_dir parameter points to the manager bundle directory

### ISSUE THREAD

**Issue by ausi** [contao/manager-bundle#28]
`$container->getParameter('kernel.project_dir')` returns `/var/www/project/vendor/contao/manager-bundle` because [`Kernel::getProjectDir()` searches for the nearest *composer.json* file](https://github.com/symfony/symfony/blob/e7da63a51f6250bb69f7652bd067fc0d1623e79a/src/Symfony/Component/HttpKernel/Kernel.php#L317). As this parameter is used for `TL_ROOT`, this makes Contao 4.4-beta1 unusable in the managed edition.

I think we have to add a `getProjectDir()` method to the `ContaoKernel`.

**Comment by aschempp** [comment]
Checking with Symfony: https://github.com/symfony/symfony/pull/22315#pullrequestreview-36763781

**Comment by leofeyer** [comment]
I have created a PR: https://github.com/symfony/symfony/pull/22727

**Comment by leofeyer** [comment]
See #29.
