### ISSUE TITLE
sporadic symlink error (file exists already)

### ISSUE THREAD

**Issue by m-vo** [contao/manager-bundle#32]
When ``ScriptHandler::initializeApplication()`` gets executed during a composer operation, I've come across this problem (had it two or three times before but unfortunately don't know by what it's caused):

````
WARNING   ContaoCoreBundle                absolute symlink
WARNING   ContaoCommentsBundle            absolute symlink
ERROR     ContaoNewsletterBundle          Failed to create "web/bundles/contaonewsletter": mkdir(): File exists.
````
(Output is from a console under windows - so that's why there are absolute symlinks and the warnings are as expected.) 

One of the symlinks cannot be created. I don't know why composer tries to create the symlink in the first place as it is already existing and I don't know why the problem only happens for one of the packages.

**Comment by m-vo** [comment]
This might probably rather be a symfony problem than a contao issue as it happens in the ``assets:install --symlink --relative`` command.

**Comment by aschempp** [comment]
is the target an existing symlink or an actual folder?

**Comment by m-vo** [comment]
An existing symlink.

**Comment by m-vo** [comment]
I now ran ``vendor/bin/contao-console assets:install --symlink --relative`` lots of times in a row.

Findings:
- the problem appears quite often. 1 out of 10 or so ;-)
- it's only the newsletter bundle that fails every single time

Is there a way to get more verbose output on the error?

**Comment by fritzmg** [comment]
> Is there a way to get more verbose output on the error?

Yes, with `-v`, `-vv` and `-vvv` ;)

**Comment by m-vo** [comment]
This never appeared again. I am therefore closing it.
