### ISSUE TITLE
Passwort setzen für app_dev besser beschreiben

### ISSUE THREAD

**Issue by BugBuster1701** [contao/manager-bundle#40]
```
/* Use the "contao:install-web-dir" console command to set a password for the dev entry point. */
```
Damit können die wenigsten (neuen) Nutzer was anfangen. Ich selber musste per "help" auch erst schauen wie das gehen soll. Wer Symfony 3.3 noch nicht kennt, wird hier nicht schlau daraus.

So könnte das schon verständlicher sein,
`contao:install-web-dir --user=USER --password[=PASSWORD]`
 sofern jeder weiß wie die contao-console aufzurufen ist.

Beachte dabei aber auch https://github.com/contao/manager-bundle/issues/39

**Comment by aschempp** [comment]
Wo hast du diese Meldung erhalten?

**Comment by fritzmg** [comment]
@aschempp https://github.com/contao/manager-bundle/blob/4.4.1/src/Resources/web/app_dev.php#L23

**Comment by aschempp** [comment]
Ah! Ich denke dazu sollte man besser was in's Handbuch schreiben, oder?

**Comment by fritzmg** [comment]
Naja ich würd entweder den Kommentar auf
```
/***********************************************************************************************/
/*                               ###  READ FIRST  ###                                          */
/* Access to debug front controllers must only be allowed on localhost or with authentication. */
/* Use the "contao:install-web-dir --user=USER --password[=PASSWORD]" console command to set a */
/* password for the dev entry point.                                                           */
/***********************************************************************************************/
```
ändern oder das Command umprogrammieren, sodass immer nach Benutzer Name und Passwort gefragt wird - außer es wurde `--no-dev` benutzt.

**Comment by BugBuster1701** [comment]
Die Nutzer bekommen ja beim Versuch es [hier](https://github.com/contao/manager-bundle/blob/4.4.1/src/Resources/web/app_dev.php#L38) angezeigt, sie sollen in diese Datei schauen, also tun die das auch.

**Comment by BugBuster1701** [comment]
Daher Kommentar erweitern und im Handbuch kanns es auch nicht schaden.

**Comment by aschempp** [comment]
Fixed in f081310
