### ISSUE TITLE
fatal error during cache:clear when manually uninstalling an extension

### ISSUE THREAD

**Issue by ghost** [contao/manager-bundle#42]
<a href="https://github.com/fritzmg"><img src="https://avatars0.githubusercontent.com/u/4970961?v=4" align="left" width="42" height="42"></img></a> [Issue](https://github.com/contao/core-bundle/issues/972) by @fritzmg
July 18th, 2017, 13:32 GMT

Tested with the contao/managed-edition 4.4.1.

### Reproduction

1. Manually install a Contao 3 extension that is compatible with Contao 4 by copying the extension folder to `/system/modules`.
2. Clear the cache.
3. Run the Install Tool.
4. Delete the extension folder from `/system/modules` again to uninstall the extension.
5. Run `vendor/bin/contao-console cache:warmup` or `… cache:clear --no-warmup` or `… cache:clear`. The following fatal error will occur:
```
PHP Fatal error:  Uncaught LogicException: The module folder "system/modules/news_sorted" does not exist. in …\vendor\contao\core-bundle\src\HttpKernel\Bundle\ContaoModuleBundle.php:36
Stack trace:
#0 …\vendor\contao\manager-plugin\src\Bundle\Config\ModuleConfig.php(53): Contao\CoreBundle\HttpKernel\Bundle\ContaoModuleBundle->__construct('news_sorted', 'C:\\xampp\\htdocs...')
#1 …\vendor\contao\manager-bundle\src\HttpKernel\ContaoKernel.php(232): Contao\ManagerPlugin\Bundle\Config\ModuleConfig->getBundleInstance(Object(Contao\ManagerBundle\HttpKernel\ContaoKernel))
#2 …\vendor\contao\manager-bundle\src\HttpKernel\ContaoKernel.php(53): Contao\ManagerBundle\HttpKernel\ContaoKernel->addBundlesFromPlugins(Array)
#3 …\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php(450): Contao\ManagerBundle\HttpKernel\ContaoKernel->registerBundles()
#4 …\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\K in …\vendor\contao\core-bundle\src\HttpKernel\Bundle\ContaoModuleBundle.php on line 36
```
The only way to uninstall such an extension is by deleting the extension folder and then deleting `var/cache/prod` manually.

**Comment by ghost** [comment]
<a href="https://github.com/aschempp"><img src="https://avatars0.githubusercontent.com/u/1073273?v=4" align="left" width="42" height="42"></img></a> Comment by @aschempp
July 18th, 2017, 13:58 GMT

This is a manager-bundle issue not core-bundle. 

No idea how to fix though 😔

**Comment by ghost** [comment]
<a href="https://github.com/fritzmg"><img src="https://avatars0.githubusercontent.com/u/4970961?v=4" align="left" width="42" height="42"></img></a> Comment by @fritzmg
July 18th, 2017, 14:00 GMT

Hm, true, in the standard-edition it would not happen, because you would have to manually remove it from the AppKernel anyway.

**Comment by leofeyer** [comment]
Which is probably one of the reasons why Symfony does not implement bundle autoloading.

**Comment by fritzmg** [comment]
Installing a Contao 3 extension that is compatible with Contao 4 via
```
composer require …
```
then setting it up in the Install Tool and then again deinstalling it via
```
composer remove …
```
causes no trouble during the `cache:clear` operation. This is because `ScriptHandler::initializeApplication` manually clears the cache (`ScriptHandler::purgeCacheFolder`) before any of the other operations.

**Comment by aschempp** [comment]
You're right. So this is actually not a bug, if you manually delete an extension folder you need to manually remove the cache…
