### ISSUE TITLE
Requirements php 7.1

### ISSUE THREAD

**Issue by rabauss** [contao/manager-bundle#49]
the composer.json should require php 7.1 because in php 7.0 we cannot install contao at the moment because of ``"symfony/console": "^3.3.7"`` in contao-core requirements!

**Comment by fritzmg** [comment]
Why? The minimum PHP version for `"symfony/console": "^3.3.7"` is `"php": "^5.5.9|>=7.0.8"`.

**Comment by leofeyer** [comment]
You probably ran into this: https://github.com/contao/managed-edition/issues/25
