### ISSUE TITLE
Update monolog-bundle to v3 in hotfix branch

### ISSUE THREAD

**Issue by Toflar** [contao/manager-bundle#52]
Otherwise Contao 4.4 ME won't be compatible with php 7.2 :)

**Comment by leofeyer** [comment]
Fixed in 6e192035ca5f02191c6079e3cc03e1c2f84d31bc.

**Comment by Toflar** [comment]
Sure you still want to allow 2.x? You‘re increasing dependency hell probably for no reason :)

**Comment by leofeyer** [comment]
Not sure at all! @contao/developers Are you ok with dropping version 2?

**Comment by ausi** [comment]
If it is compatible with 3.x and there is no specific reason to drop 2.x I think it should stay.

**Comment by aschempp** [comment]
I think we can drop 2.x it in Contao 4.5, but not in the LTS version.

**Comment by leofeyer** [comment]
Ok, that's the status quo then.
