### ISSUE TITLE
PHP error on first run in Plugin.php

### ISSUE THREAD

**Issue by damianon** [contao/manager-bundle#55]
After downloading contao 4.5.3 (manually) and extracting, pointing DocumentRoot to the web/ dir and calling /install.php I get this error 

`Parse error: syntax error, unexpected '?' in /data/web/sgcontao/vendor/contao/manager-bundle/src/ContaoManager/Plugin.php on line 137`

Line 137 looks like this:
` public function getRouteCollection(LoaderResolverInterface $resolver, KernelInterface $kernel): ?RouteCollection`

Running on Ubuntu 16.04. with php 7.0

**Comment by fritzmg** [comment]
Contao 4.5 requires at least PHP 7.1
