### ISSUE TITLE
Allow to disable HttpCache

### ISSUE THREAD

**Issue by Toflar** [contao/manager-bundle#62]
We should be able to circumvent the default AppCache by an env variable in case you want to use a real reverse proxy (Varnish, Litespeed etc.) in front of Contao.

**Comment by aschempp** [comment]
Waiting for https://github.com/contao/manager-bundle/pull/68 as it implements same changes to the `app.php` and `app_dev.php` files.

**Comment by aschempp** [comment]
see https://github.com/contao/manager-bundle/pull/71
