### ISSUE TITLE
Contao 4.4.17 & Symfony 3.4.8 error: "A Token was not found in the TokenStorage"

### ISSUE THREAD

**Issue by Xendiadyon** [contao/manager-bundle#65]
As written in https://github.com/contao/manager-bundle/issues/61 there is still a problem with Contao 4.4.* and Symfony 3.4.8+:

![image](https://user-images.githubusercontent.com/2657385/38492265-b347e222-3bee-11e8-948b-3d4f91ab9f16.png)

**Comment by fritzmg** [comment]
Just made a ticket here too: https://github.com/contao/core-bundle/issues/1466 ;)
