### ISSUE TITLE
If the .htaccess already exist contao is not placing its own

### ISSUE THREAD

**Issue by netzarbeiter** [contao/manager-bundle#70]
Some Webhoster are adding a `.htaccess` with an `AddHandler` in the web-folder if you change the PHP version.

For example: `AddHandler application/x-httpd-php72 .php`

Is it possible to merge the AddHandler during the creation of the `.htaccess` and overwrite the old version.

While testing the new Contao Manager everything went well, expect updating the database (domain.com/contao/install), while the needed lines in the .htaccess were missing.

**Comment by Toflar** [comment]
I think that's a quite common case @contao/developers. If the .htaccess only contains `AddHandler`, I think we could add that, wdyt?

**Comment by m-vo** [comment]
I don't think merging an `.htaccess` file is a good idea. There is too much that could go wrong. 

(That by the way is another reason why shipping that file is problematic / related disucssion: #58)

**Comment by Toflar** [comment]
I would do it only if `AddHandler` and only if `AddHandler` is present. As soon as there's other content in there, I wouldn't do anything at all.

**Comment by m-vo** [comment]
Yeah, that would be fine then, I guess. We have to be careful, though. If something in the lines we're adding affects this php setting (and if it's presence is neccessary by the hoster), the server might e.g. deliver unparsed PHP.

**Comment by Toflar** [comment]
The `AddHandler` case is just very, very common for virtual hosts, that's why I think that might be worth an exception.

**Comment by leofeyer** [comment]
> I don't think merging an `.htaccess` file is a good idea. There is too much that could go wrong. 

I fully agree with this. We must not mess with an existing `.htacces` file!

**Comment by netzarbeiter** [comment]
If you don't want to mess with an existing `.htaccess`, the Contao Manager should display a warning that the `.htaccess` could not have been written and were they get it from.

**Comment by zonky2** [comment]
maybe it´s possible to write `.htaccess-contao` if another htaccess exist - it´s easier to copy one content to another htaccess...

**Comment by leofeyer** [comment]
As discussed in Mumble on August 30th, we want to check the existing [`.htaccess`](https://github.com/contao/manager-bundle/blob/master/src/Resources/skeleton/web/.htaccess) file for

`/^\s*RewriteRule\s/im`

and if there is no match, we want to append the .htaccess content. Additionally, we want to provide a `.htaccess.default` file, so people can look up what needs to be added.

**Comment by Toflar** [comment]
PR ready: https://github.com/contao/contao/pull/160

**Comment by leofeyer** [comment]
Thank you @Toflar. 👍
