### ISSUE TITLE
Preview maintenance mode locally

### ISSUE THREAD

**Issue by m-vo** [contao/manager-bundle#78]
In 423a6831d9a25c0cfe165f4ef537165aff8a3536 the default configuration for authorized ips (lexik maintenance bundle) has been set to `['127.0.0.1']` as a quick fix for https://github.com/contao/core-bundle/issues/1492. 

How am I supposed to test the maintenance mode locally now (e.g. when working on a custom `service_unavailable` template) besides temporarily removing the setting again in my config like so (with the implications of the referenced ticket)? 

```yml
lexik_maintenance:
    authorized:
        ips: []
```

btw.: The related PR in Symfony https://github.com/symfony/symfony/pull/27309 that was in the way and leaded to the quickfix has been merged in 3.4.12.

**Comment by leofeyer** [comment]
We can revert the [intermediate fix](https://github.com/contao/manager-bundle/commit/c42899bb57566b414dbaf8a1719e028eac2befdc) now.

**Comment by leofeyer** [comment]
Reverted in 5768cfec7aa7b46368d3466e330ca2e1e9e0ee5d.
