### ISSUE TITLE
Docu

### ISSUE THREAD

**Issue by twiesing** [contao/manager-bundle#81]
hey,

when do you provide an up 2 date documentation for contao 4.5? =)
e.g. php requirements are outdated....

https://docs.contao.org/books/manual/current/de/01-installation/den-live-server-konfigurieren.html#contao-systemvoraussetzungen

**Comment by xchs** [comment]
See https://github.com/contao/docs/pull/484

**Comment by m-vo** [comment]
@fritzmg and @netzarbeiter are on it and it's going to be a-ma-zing. :smiley:.
