### ISSUE TITLE
Symfony 5 is required for Monolog 2 support. 

### ISSUE THREAD

**Issue by AgenceUpMotion** [contao/manager-bundle#86]
**Affected version(s)**
Contao 4.4.45
Php 7.3.5

**Description**  

During the installation I have this error
In ScriptHandler.php line 113:

An error occurred while executing the "contao:install-web-dir" command:
In MonologExtension.php line 55:

Symfony 5 is required for Monolog 2 support. Please downgrade Monolog to
version 1.

**How to reproduce**

**Comment by fritzmg** [comment]
Run the composer update again. It should be fixed with https://github.com/contao/conflicts/commit/99f14df05740a7d0818735e1dead739a59af73c6

**Comment by AgenceUpMotion** [comment]
Thanks @fritzmg
