### ISSUE TITLE
.env files are ignored when using the symfony binary

### ISSUE THREAD

**Issue by m-vo** [contao/manager-bundle#87]
If `$_SERVER['APP_ENV']` ist set, loading of the `.env` files is currently prevented in our Kernel:

https://github.com/contao/manager-bundle/blob/b5b9a22225a1cda6aed3d9337f645d11efbe1cc9/src/HttpKernel/ContaoKernel.php#L380-L383

This leads to a bad dx when using the symfony binary to execute the console ( as a [wrapper for php to get a consistent version](https://symfony.com/doc/current/setup/symfony_server.html#running-commands-with-different-php-versions)) because the symfony binary is apparently setting `$_SERVER['APP_ENV'] = 'prod'` by default:

```bash
symfony php vendor/bin/contao-console # <-- won't process .env / .env.local
php vendor/bin/contao-console         # <-- will process .env / .env.local
```

In a Symfony 5 application (with flex) the `.env` files are processed anyways, also the default bootstrapping ([see recipe](https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/4.2/config/bootstrap.php)) for Symfony 4 doesn't contain this check. 

I'd really like the managed edition and flex behave the same way in this case. Although I don't really know what the correct behavior should be.

**Comment by Toflar** [comment]
Symfony Flex does default to `dev`, the Managed Edition to `prod`. Both for very good reasons.

**Comment by leofeyer** [comment]
I doubt that we can do anything about it, because we do need this check in case real env variables are used. @aschempp /cc

**Comment by m-vo** [comment]
I don't really get why the ME cannot behave the same as a flex app? Imo this doesn't have to do with the defaults but maybe I'm missing something. :smile:

**Comment by Toflar** [comment]
I have already described why it doesn‘t work?

**Comment by leofeyer** [comment]
It is still confusing. Maybe we can improve the DX here?

**Comment by leofeyer** [comment]
As discussed in Mumble on August 27th, we should always load the `.env` file (even if `APP_ENV` is set), because DotEnv will no longer overwrite existing variables.

**Comment by leofeyer** [comment]
See https://github.com/contao/contao/pull/2208
