### ISSUE TITLE
Problem using PHP 7.4 - FOS/http-cache-bundle issue

### ISSUE THREAD

**Issue by qbadev** [contao/manager-bundle#89]
Have:
- server Ubuntu 20.04 x64
- PHP 7.4.15
- Contao latest managed-edition
- FOS/http-cache-bundle 2.10.2
When trying to run installer, I receive error:
```request.CRITICAL: Uncaught PHP Exception Exception: "Php8AttributesListener must not be loaded for PHP 7.4.15" at vendor/friendsofsymfony/http-cache-bundle/src/EventListener/Php8AttributesListener.php line 35 {"exception":"[object] (Exception(code: 0): Php8AttributesListener must not be loaded for PHP 7.4.15 at vendor/friendsofsymfony/http-cache-bundle/src/EventListener/Php8AttributesListener.php:35)"} []```
Quick investigation shows, that `Php8AttributesListener` must be loaded only for PHP 8.
Why is it being loaded with Contao core, when in 7.4 environment?

**Comment by Toflar** [comment]
Apparently you installed Contao/built the cache using PHP 8 instead of 7.4?

**Comment by qbadev** [comment]
that might be, as I have web php 7.4, and CLI 8.0

**Comment by Toflar** [comment]
You have the answer to your question then? :) 
Contao as well as many other Symfony bundles and the Symfony full stack framework itself ensure optimal configuration during cache build time. They also check for available php extensions to make sure they can make the best out of the available platform. You must use the same PHP configuration (extensions and version) when building it (or running any CLI commands for that matter).

**Comment by qbadev** [comment]
Yes, that's clear, I always keep it clean and updated, but this time Automatic Updates of Ubuntu made a mess. Thanks for pointing me to the right direction.
