### ISSUE TITLE
Some questions :)

### ISSUE THREAD

**Issue by leofeyer** [contao/manager-bundle#9]
1. Why is the `bin/contao-console` command not named `bin/console`?

2. Why did you add `AnnotationRegistry::registerLoader([$loader, 'loadClass']);` in the console script?

3. Why is the `src/Resources/web/.htaccess.default` file not named `.htaccess` and only copied if no `.htaccess` file exists? Is "having a custom `.htaccess`" file a supported case at all?

**Comment by aschempp** [comment]
1. I think the file should actually live in `Resources/bin/console` like `web` does

 2. because we don't have an `app/autoload.php`

 3. custom `.htaccess` is a requirement, I stumbled upon this quickly. For example a lot of hosting providers adjust that file to enable different php versions.
