### ISSUE TITLE
Where is the config/ directory in fresh 4.12 installation ?

### ISSUE THREAD

**Issue by benjamindulau** [contao/manager-bundle#90]
Hi,

Trying to install contao 4.12 with composer:
```
$ composer create-project contao/managed-edition xxxx 4.12
```

After that the `config/` directory is totally absent from the file tree (as is the config/config.yml file).
```
[vagrant@localhost - contao4]$ ls -ltha
total 476K
drwxrwxr-x. 13 501 games  416  2 déc.  09:53 .
drwxrwxr-x. 11 501 games  352  2 déc.  09:39 public
-rw-rw-r--.  1 501 games   93  2 déc.  09:14 .env
drwxrwxr-x.  5 501 games  160  2 déc.  09:11 var
drwxrwxr-x.  9 501 games  288  2 déc.  09:10 system
drwxrwxr-x.  2 501 games   64  2 déc.  09:10 files
drwxrwxr-x. 21 501 games  672  2 déc.  09:10 assets
drwxrwxr-x.  2 501 games   64  2 déc.  09:10 templates
drwxrwxr-x. 50 501 games 1,6K  2 déc.  09:09 vendor
-rw-rw-r--.  1 501 games 463K  2 déc.  09:09 composer.lock
drwxr-xr-x. 19 501 games  608  2 déc.  09:09 ..
-rw-rw-r--.  1 501 games  821 24 août  09:06 composer.json
-rw-rw-r--.  1 501 games  313 24 août  09:06 .gitignore
```

The documentation often refers to the config file. Do we have to create that file manually?

The documentation also states that le install tool is responsible of creating a `config/parameters.yml`. I did not use the install tool but exclusively the CLI. I created an .env file to override database DSN.

Since the config file doesn't exist, where are we supposed to tweak symfony and packages configuration?

There are some inconsistency in the documentation regarding which files contao would create for us and which files the developer should create manually.

**Comment by fritzmg** [comment]
> Do we have to create that file manually?

Yes, the `config/config.yaml` needs to be created manually. So does the `config/` folder - depending on whether you already ran the install tool or not.

**Comment by benjamindulau** [comment]
Ok I just read the System > Settings manual's chapter.
That makes more sense.

We massively used Contao 3.x and we're glad to see that Contao tends to follow standards and is progressively cleaning up legacy configuration logic.

Thanks.
Closing
